---
title: "SEKI"
author: "Ethan"
date: "3/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

library(tidyverse)
library(janitor)
library(stringr)
library(sjmisc)
library(readr)

```

## R Data

```{r raw, message=FALSE, warning=FALSE}

raw <- read_csv("data/raw/SEKI Data Mar 16.csv")
```


```{r datacleaning, message=FALSE, warning=FALSE}



df <- clean_names(raw)

question_numbers <- colnames(df[, 18:365])

df <- df %>% row_to_names(row = 1)
df <- df[-1,]

partnerquestions <- df[, 18:365]
firstquestion <- df[, 1:17]
partnerquestions <- colnames(partnerquestions)
partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "Generally speaking and thinking of a recent and typical fiscal year, ",
        replacement = "",
        x = t,
        fixed = TRUE
      )
  )
partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "(financial, time, labor, etc.) are allocated to these fire-related issues:",
        replacement = "are allocated to",
        x = t,
        fixed = TRUE
      )
  )
partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "across the PACE\n\n\n\nBelow, you will see a list of California State and Federal agencies that work within and across the Sequoia & Kings Canyon (SEKI) geography of interest. \n\n\n\nPlease consider with whom you go to fire-related meetings, receive or share advice or information, or implement projects within or across the PACE. Select all that apply. - ",
        replacement = "",
        x = t,
        fixed = TRUE
      )
  )
partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "Among the list below, please consider with whom you go to fire-related meetings, receive or share advice or information, or implement projects within or across the PACE. Select all that apply.",
        replacement = "",
        x = t,
        fixed = TRUE
      )
  )

partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "Continued: Information sharing and collaboration networks across the PACE\n\n\n\nBelow, you will see a list of agencies and ",
        replacement = "",
        x = t,
        fixed = TRUE
      )
  )

partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "\nCommunication (we make sure partnering entities know what we're doing), \n\nCoordination (we make sure partnering entities know what we're doing, consult them in planning, and try to schedule our independent activities to achieve synergies), and \n\nCollaboration (we communicate and plan together, and try to share resources where possible, within constraints imposed by laws or regulations). -",
        replacement = "",
        x = t,
        fixed = TRUE
      )
  )


partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "\nCommunication (we make sure partnering entities know what we're doing), \n\nCoordination\n (we make sure partnering entities know what we're doing, consult them \nin planning, and try to schedule our independent activities to achieve \nsynergies), and \n\nCollaboration\n (we communicate and plan together, and try to share resources where \npossible, within constraints imposed by laws or regulations). -",
        replacement = "",
        x = t,
        fixed = TRUE
      )
  )


partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "The record-setting 2020 California wildfire season included nearly \n10,000 fires, the largest recorded wildfire in the state, and the most \nacres burned in a season (over 4.2 million acres). \n\n",
        replacement = "",
        x = t,
        fixed = TRUE
      )
  )

partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "Section 2: Information sharing and collaboration networks ",
        replacement = "",
        x = t,
        fixed = TRUE
      )
  )

partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "organizations that don't have a defined jurisdiction in the SEKI PACE, but may be a part of your network.  - ",
        replacement = "",
        x = t,
        fixed = TRUE
      )
  )

partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "Continued: Information sharing and collaboration networks across the PACE\n\n\n\nPlease list additional organizations/groups below. - ",
        replacement = "",
        x = t,
        fixed = TRUE
      )
  )


partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "Indicate which fire management issue(s) is the focus of your interactions: - ",
        replacement = "",
        x = t,
        fixed = TRUE
      )
  )



partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "How would you characterize your interaction with the following entities: ",
        replacement = "",
        x = t,
        fixed = TRUE
      )
  )

 partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "Please rate your level of satisfaction with the joint activities to increase the capacity to prepare for and respond to fire. Your answers are confidential. - ",
        replacement = "",
        x = t,
        fixed = TRUE
      )
  )

 partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "Please rate your level of satisfaction \nwith the range of actions taken by partnering with this entity to \nincrease the capacity to prepare and respond to fire (your answers are confidential). - ",
        replacement = "",
        x = t,
        fixed = TRUE
      )
  )
 
  partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "Generally speaking, the information provided by the following organizations is: - ",
        replacement = "",
        x = t,
        fixed = TRUE
      )
  )
  
   partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "I estimate the likelihood of fire spreading to other jurisdictions from ______ is: - ",
        replacement = "",
        x = t,
        fixed = TRUE
      )
  )
 
   partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "How confident are you in the planning and operational capacity of the jurisdiction to prevent ignition or limit the spread of a large fire? - ",
        replacement = "",
        x = t,
        fixed = TRUE
      )
  )   
   
   

  
     partnerquestions <-
  sapply(
    X = partnerquestions,
    FUN = function(t)
      gsub(
        pattern = "How relevant was each partnership in dealing with the conditions in 2020? - ",
        replacement = "",
        x = t,
        fixed = TRUE
      )
  )   

   
concatquestions <- paste(question_numbers, partnerquestions)
partnerquestions <- df[, 18:365]
colnames(partnerquestions) <- concatquestions
df <- bind_cols(firstquestion, partnerquestions)

df <- df[-c(1:17, 20:30, 68)]

df$network_level <- ""

df <- df %>% rename("ego" = "q1_2 What is the name of the agency or organization you are completing this survey on behalf of? Please be as specific as possible (e.g., Bishop Field Office of Bureau of Land Management)"
  ) 



```




```{r egofiing, message=FALSE, warning=FALSE}


df_long <- df %>% tidyr::pivot_longer(cols = c(3:49),
                                           names_to = "alter",
                                           values_to = "function") %>% mutate(
                                             communication = 0,
                                             ecology = 0,
                                             education = 0,
                                             mapping = 0,
                                             operations = 0,
                                             air_quality = 0,
                                             mechanical_treatments = 0,
                                             prescribed_fire = 0,
                                             restoration = 0
                                             
                                           ) %>%  select(
                                             ego,
                                             alter,
                                             `function`,
                                             network_level,
                                             communication,
                                             ecology,
                                             education,
                                             mapping,
                                             operations,
                                             air_quality,
                                             mechanical_treatments,
                                             prescribed_fire,
                                             restoration,
                                             everything()
                                           ) %>% drop_na(`function`)

df_long$network_level[startsWith(df_long$alter, "q2_1")] <- "SEKI - Defined"
df_long$network_level[startsWith(df_long$alter, "q2_2")] <- "SEKI - Undefined"
df_long$network_level[startsWith(df_long$alter, "q2_4")] <- "SEKI - Other"


#This regex removes the first word, or group of characters from string
df_long$alter <- sub("\\S+\\s+", "", df_long$alter)


network_level <- select(df_long, ego, alter, `function`, network_level)





```



```{r issues, message=FALSE, warning=FALSE}

issues <- df %>% tidyr::pivot_longer(cols = c(50:96),
                                     names_to = "alter",
                                     values_to = "function")  %>% mutate(
                                       communication = 0,
                                       ecology = 0,
                                       education = 0,
                                       mapping = 0,
                                       operations = 0,
                                       air_quality = 0,
                                       mechanical_treatments = 0,
                                       prescribed_fire = 0,
                                       restoration = 0
                                     ) %>% select(
                                       ego,
                                       alter,
                                       `function`,
                                       communication,
                                       ecology,
                                       education,
                                       mapping,
                                       operations,
                                       air_quality,
                                       mechanical_treatments,
                                       prescribed_fire,
                                       restoration,
                                       everything()
                                     ) %>% drop_na(`function`)

issues$alter <- sub("\\S+\\s+", "", issues$alter)


for (i in 1:length(issues$`function`)) {
  function_list <- as.list(strsplit(issues$`function`[i], ","))
  
  for (j in 1:length(function_list[[1]])) {
    if (function_list[[1]][[j]] == "Fire ecology") {
      issues$ecology[i] <- 1
    }
    else if (function_list[[1]][[j]] == "Fire communication") {
      issues$communication[i] <- 1
    }
    else if (function_list[[1]][[j]] == "Fire communication and education") {
      issues$communication[i] <- 1
      issues$education[i] <- 1
    }
    else if (function_list[[1]][[j]] == "Fire education") {
      issues$education[i] <- 1
    }
    else if (function_list[[1]][[j]] == "Fire mapping and GIS") {
      issues$mapping[i] <- 1
    }
    else if (function_list[[1]][[j]] == "Fire operations and crews") {
      issues$operations[i] <- 1
    }
    else if (function_list[[1]][[j]] == "Fire-related air quality") {
      issues$air_quality[i] <- 1
    }
    else if (function_list[[1]][[j]] == "Fuels management-mechanical treatments") {
      issues$mechanical_treatments[i] <- 1
    }
    else if (function_list[[1]][[j]] == "Fuels management-prescribed fire") {
      issues$prescribed_fire[i] <- 1
    }
    else if (function_list[[1]][[j]] == "Post-fire mitigation and restoration") {
      issues$restoration[i] <- 1
    }
  }
  
}

issues <- issues %>% select(
  ego,
  alter,
  communication,
  ecology,
  education,
  mapping,
  operations,
  air_quality,
  mechanical_treatments,
  prescribed_fire,
  restoration
)

strength <- df %>% select(ego, 97:143) %>% pivot_longer(
  cols = c(
    `q2_6_x25  BLM-Bishop Field Office`:`null_x25_2  Group #10`
  ),
  names_to = "alter",
  values_to = "strength"
) %>% select(ego, alter, strength) %>% drop_na(strength)

strength$alter <- sub("\\S+\\s+", "", strength$alter)


satisfaction <- df %>% select(ego, 144:190) %>% pivot_longer(
  cols = c(`q3_1_x25 BLM-Bishop Field Office`:`null_x25_4 Group #10`),
  names_to = "alter",
  values_to = "satisfaction"
) %>% select(ego, alter, satisfaction) %>% drop_na(satisfaction)

satisfaction$alter <- sub("\\S+\\s+", "", satisfaction$alter)


quality <- df %>% select(ego, 191:237) %>% pivot_longer(
  cols = c(`null_x25_5 BLM-Bishop Field Office`:`null_x25_7 Group #10`),
  names_to = "alter",
  values_to = "quality"
) %>% select(ego, alter, quality) %>% drop_na(quality)

quality$alter <- sub("\\S+\\s+", "", quality$alter)


fire_spread <- df %>% select(ego, 238:253) %>% pivot_longer(
  cols = c(`null_x25_8 BLM-Bishop Field Office`:`null_x41_1 USFS-Sierra National Forest-High Sierra`),
  names_to = "alter",
  values_to = "fire_spread"
) %>% select(ego, alter, fire_spread) %>% drop_na(fire_spread)

fire_spread$alter <- sub("\\S+\\s+", "", fire_spread$alter)

operational_capacity <- df %>% select(ego, 254:269) %>% pivot_longer(
  cols = c(`null_x25_9 BLM-Bishop Field Office`:`null_x41_2 USFS-Sierra National Forest-High Sierra`),
  names_to = "alter",
  values_to = "operational_capacity"
) %>% select(ego, alter, operational_capacity) %>% drop_na(operational_capacity)

operational_capacity$alter <- sub("\\S+\\s+", "", operational_capacity$alter)

relevance <- df %>% select(ego, 270:306) %>% pivot_longer(
  cols = c(`null_x25_10 BLM-Bishop Field Office`:`q141_x48 Yokut (Native American Indigenous Peoples)`),
  names_to = "alter",
  values_to = "relevance"
) %>% select(ego, alter, relevance) %>% drop_na(relevance)

relevance$alter <- sub("\\S+\\s+", "", relevance$alter)


edge_data <-
  left_join(issues, strength, by = c("ego", "alter")) %>% left_join(., satisfaction, by = c("ego", "alter")) %>% left_join(., quality, by = c("ego", "alter")) %>% left_join(., fire_spread, by = c("ego", "alter")) %>% left_join(., operational_capacity, by = c("ego", "alter")) %>% left_join(., relevance, by = c("ego", "alter")) %>% left_join(., network_level, by = c("ego", "alter")) 

edge_data <- edge_data[!duplicated(edge_data[,c('ego', 'alter')]),] 

 #Fixing alters for those that are in the "Other" category 
 for(i in 1:length(edge_data$`function`)) {
   if (edge_data$`function`[i] != "Partner") {
     edge_data$alter[i] <- edge_data$`function`[i]
   }
 }

edge_data <- edge_data %>% select(ego, alter, network_level, everything()) %>% select(-c(`function`))

write.csv(edge_data, "data/processed/edgelist.csv")
```


```{r visnetwork}
library(igraph)
library(visNetwork)

g1<-graph_from_data_frame(d=edge_data,directed=TRUE) 

#Degree in 
inDegree<-igraph::degree(g1,mode="in")
outDegree<-igraph::degree(g1,mode="out")
TotalDegree<-as.data.frame(igraph::degree(g1))
betweenness<-igraph::betweenness(g1, v = V(g1), directed = TRUE, weights = NULL,
  nobigint = TRUE, normalized = TRUE)
inCloseness<-igraph::closeness(g1, vids = V(g1), mode = c("in"),normalized = TRUE)
outCloseness<-igraph::closeness(g1, vids = V(g1), mode = c("out"),normalized = TRUE)
#eigen<-evcent(m1,g=1,gmode = "digraph",rescale=TRUE, ignore.eval=TRUE)
#removed eigen from this DF_Centrality
DF_Centrality<-as.data.frame(cbind(rownames(TotalDegree),inDegree,outDegree,TotalDegree,betweenness,inCloseness,outCloseness))
rownames(DF_Centrality)<-NULL
DF_Centrality<-as.data.frame(DF_Centrality)
colnames(DF_Centrality)[1]<-"name"
colnames(DF_Centrality)[4]<-"TotalDegree"

DF_Centrality <- DF_Centrality %>%  select(name, TotalDegree) %>% rename("id" = "name", "size" = "TotalDegree" )


gvis<-toVisNetworkData(g1)

nodes <- gvis$nodes
nodes <- nodes %>% left_join(DF_Centrality) %>% mutate(color = "#EE4B2B")

SEKI_network <-
  visNetwork(
    nodes,
    gvis$edges,
    main = "SEKI PACE Network",
    width = "100%",
    height = "850px"
  ) %>%
  visEdges(
    smooth = T,
    arrows = list(
      to = list(enabled = TRUE, scaleFactor = .5),
      width = 3
    ),
    color = list(highlight = "black")
  ) %>% 
  visNodes(color = list(
    background = "white",
    border = "black",
    highlight = list(background = "#A9A9A9", border = "black"),
    hover = list(background = "#A9A9A9", border = "black")
  )) %>%
  visPhysics(stabilization = FALSE)  %>%
  visIgraphLayout(
    smooth = FALSE,
    physics = FALSE,
    layout = "layout_with_fr",
    randomSeed = 27
  ) %>%
  visInteraction(navigationButtons = TRUE)


SEKI_network
  
```